# Use official Python image
FROM python:3.10-slim

# Set the working directory inside the container
WORKDIR /app

# Install test dependencies from requirements.txt inside the /tests directory
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire project code into the container
COPY .. /app

# Set PYTHONPATH to ensure Python can find modules
ENV PYTHONPATH=/app

# Command to run tests with pytest
CMD ["pytest", "--maxfail=1", "--disable-warnings", "-v"]
