services:
  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    ports:
      - "80:80" # Expose port 80 for both frontend and backend API
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Nginx configuration
    depends_on:
      - frontend
      - frontend_api
    networks:
      - internal_network

  db:
    image: mongo:4.4
    container_name: mongo_db
    volumes:
      - mongo_data:/data/db
    networks:
      - internal_network

  db_api:
    build: ./db_api
    container_name: db_api_service
    ports:
      - "8000:8000" # Expose db_api internally, mapped to port 8000
    environment:
      - MONGO_URL=mongodb://db:27017 # MongoDB URL for db_api
    depends_on:
      - db
    networks:
      - internal_network

  scraper:
    build: ./scraper
    container_name: scraper
    environment:
      - DB_API_URL=http://db_api_service:8000
    depends_on:
      - db_api
    networks:
      - internal_network

  frontend_api:
    build: ./frontend_api
    container_name: frontend_api_service
    ports:
      - "8003:8003" # Expose frontend_api on port 8003
    environment:
      - DB_API_URL=http://db_api_service:8000 # Ensure frontend_api points to db_api
    depends_on:
      - db_api
      - frontend
    networks:
      - internal_network

  frontend:
    build: ./frontend_vue
    container_name: frontend_service
    environment:
      - VUE_APP_API_URL=http://frontend_api_service:8003

    networks:
      - internal_network

volumes:
  mongo_data:
    driver: local

networks:
  internal_network:
    driver: bridge
