properties = [
        {
            "id": 1,
            "name": "Mechurova 23",
            "address": "Mechurova 23, Prague 4",
            "coordinates": [51.5, -0.09],
            "price": "24 400",
            "prop_type": "byt",
            "images": [
                "https://images.pexels.com/photos/259950/pexels-photo-259950.jpeg",
                "https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg",
                "https://images.pexels.com/photos/323705/pexels-photo-323705.jpeg",
            ],
            "prop_size_kk": 2,
            "prop_size_m2": 44,
            "energy_class": "B",
            "rk": True,
            "floor": 3,
            "parking": 2,
            "elevator": True,
            "features": ["Balcony", "Air Conditioning", "Central Heating"],
            "neighborhood": {
                "description": "A quiet and family-friendly neighborhood...",
                "amenities": ["School", "Park", "Shopping Center"],
                "transport": ["Bus", "Metro", "Train"],
            },
            "average_rent": "22 000 /m",
            "pricing_details": {
                "one_time_payments": [
                    {"name": "Security Deposit", "amount": "48 800 "},
                    {"name": "Agency Fee", "amount": "24 400 "},
                ],
                "monthly_payments": [
                    {"name": "Rent", "amount": "24 400 "},
                    {"name": "Utilities", "amount": "2 500 "},
                ],
            },
            "contact": {
                "agent": "John Doe",
                "phone": "+420 123 456 789",
                "email": "john.doe@example.com",
            },
        },
        {
            "id": 2,
            "name": "Lipanska 35",
            "address": "Lipanska 35, Prague 3",
            "coordinates": [51.51, -0.11],
            "price": "27 500",
            "prop_type": "office",
            "images": [
                "https://images.pexels.com/photos/2029694/pexels-photo-2029694.jpeg",
                "https://images.pexels.com/photos/6492383/pexels-photo-6492383.jpeg",
                "https://images.pexels.com/photos/1779483/pexels-photo-1779483.jpeg",
            ],
            "prop_size_kk": 3,
            "prop_size_m2": 60,
            "energy_class": "A",
            "rk": True,
            "floor": 5,
            "parking": 1,
            "elevator": False,
            "features": ["City View", "Modern Design", "High Security"],
            "neighborhood": {
                "description": "Vibrant area with numerous offices and shops...",
                "amenities": ["Cafes", "Gyms", "Banks"],
                "transport": ["Tram", "Bus"],
            },
            "average_rent": "25 000",
            "pricing_details": {
                "one_time_payments": [
                    {"name": "Security Deposit", "amount": "55 000 "},
                    {"name": "Agency Fee", "amount": "27 500 "},
                ],
                "monthly_payments": [
                    {"name": "Rent", "amount": "27 500"},
                    {"name": "Utilities", "amount": "3 000 "},
                ],
            },
            "contact": {
                "agent": "Alice Smith",
                "phone": "+420 987 654 321",
                "email": "alice.smith@example.com",
            },
        },
        {
            "id": 3,
            "name": "Radlicka 52",
            "address": "Radlicka 52, Prague 5",
            "coordinates": [51.48, -0.1],
            "price": "30 000",
            "prop_type": "house",
            "images": [
                "https://images.pexels.com/photos/1643389/pexels-photo-1643389.jpeg",
                "https://images.pexels.com/photos/259962/pexels-photo-259962.jpeg",
                "https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg",
            ],
            "prop_size_kk": 4,
            "prop_size_m2": 75,
            "energy_class": "A+",
            "rk": False,
            "floor": 2,
            "parking": 3,
            "elevator": False,
            "features": ["Garden", "Fireplace", "Spacious Rooms"],
            "neighborhood": {
                "description": "A suburban area with lots of greenery...",
                "amenities": ["Schools", "Supermarkets", "Clinics"],
                "transport": ["Bus", "Metro"],
            },
            "average_rent": "28 500",
            "pricing_details": {
                "one_time_payments": [
                    {"name": "Security Deposit", "amount": "60 000 "},
                    {"name": "Agency Fee", "amount": "30 000 "},
                ],
                "monthly_payments": [
                    {"name": "Rent", "amount": "30 000 "},
                    {"name": "Utilities", "amount": "3 500 "},
                ],
            },
            "contact": {
                "agent": "Eva Novak",
                "phone": "+420 123 123 456",
                "email": "eva.novak@example.com",
            },
        },
        {
            "id": 3,
            "name": "Radlicka 52",
            "address": "Radlicka 52, Prague 5",
            "coordinates": [51.48, -0.1],
            "price": "30 000",
            "prop_type": "house",
            "images": [
                "https://images.pexels.com/photos/1643389/pexels-photo-1643389.jpeg",
                "https://images.pexels.com/photos/259962/pexels-photo-259962.jpeg",
                "https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg",
            ],
            "prop_size_kk": 4,
            "prop_size_m2": 75,
            "energy_class": "A+",
            "rk": False,
            "floor": 2,
            "parking": 3,
            "elevator": False,
            "features": ["Garden", "Fireplace", "Spacious Rooms"],
            "neighborhood": {
                "description": "A suburban area with lots of greenery...",
                "amenities": ["Schools", "Supermarkets", "Clinics"],
                "transport": ["Bus", "Metro"],
            },
            "average_rent": "28 500",
            "pricing_details": {
                "one_time_payments": [
                    {"name": "Security Deposit", "amount": "60 000 "},
                    {"name": "Agency Fee", "amount": "30 000 "},
                ],
                "monthly_payments": [
                    {"name": "Rent", "amount": "30 000 "},
                    {"name": "Utilities", "amount": "3 500 "},
                ],
            },
            "contact": {
                "agent": "Eva Novak",
                "phone": "+420 123 123 456",
                "email": "eva.novak@example.com",
            },
        },
        {
            "id": 3,
            "name": "Radlicka 52",
            "address": "Radlicka 52, Prague 5",
            "coordinates": [51.48, -0.1],
            "price": "30 000",
            "prop_type": "house",
            "images": [
                "https://images.pexels.com/photos/1643389/pexels-photo-1643389.jpeg",
                "https://images.pexels.com/photos/259962/pexels-photo-259962.jpeg",
                "https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg",
            ],
            "prop_size_kk": 4,
            "prop_size_m2": 75,
            "energy_class": "A+",
            "rk": False,
            "floor": 2,
            "parking": 3,
            "elevator": False,
            "features": ["Garden", "Fireplace", "Spacious Rooms"],
            "neighborhood": {
                "description": "A suburban area with lots of greenery...",
                "amenities": ["Schools", "Supermarkets", "Clinics"],
                "transport": ["Bus", "Metro"],
            },
            "average_rent": "28 500",
            "pricing_details": {
                "one_time_payments": [
                    {"name": "Security Deposit", "amount": "60 000 "},
                    {"name": "Agency Fee", "amount": "30 000 "},
                ],
                "monthly_payments": [
                    {"name": "Rent", "amount": "30 000 "},
                    {"name": "Utilities", "amount": "3 500 "},
                ],
            },
            "contact": {
                "agent": "Eva Novak",
                "phone": "+420 123 123 456",
                "email": "eva.novak@example.com",
            },
        },
        {
            "id": 3,
            "name": "Radlicka 52",
            "address": "Radlicka 52, Prague 5",
            "coordinates": [51.48, -0.1],
            "price": "30 000",
            "prop_type": "house",
            "images": [
                "https://images.pexels.com/photos/1643389/pexels-photo-1643389.jpeg",
                "https://images.pexels.com/photos/259962/pexels-photo-259962.jpeg",
                "https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg",
            ],
            "prop_size_kk": 4,
            "prop_size_m2": 75,
            "energy_class": "A+",
            "rk": False,
            "floor": 2,
            "parking": 3,
            "elevator": False,
            "features": ["Garden", "Fireplace", "Spacious Rooms"],
            "neighborhood": {
                "description": "A suburban area with lots of greenery...",
                "amenities": ["Schools", "Supermarkets", "Clinics"],
                "transport": ["Bus", "Metro"],
            },
            "average_rent": "28 500",
            "pricing_details": {
                "one_time_payments": [
                    {"name": "Security Deposit", "amount": "60 000 "},
                    {"name": "Agency Fee", "amount": "30 000 "},
                ],
                "monthly_payments": [
                    {"name": "Rent", "amount": "30 000 "},
                    {"name": "Utilities", "amount": "3 500 "},
                ],
            },
            "contact": {
                "agent": "Eva Novak",
                "phone": "+420 123 123 456",
                "email": "eva.novak@example.com",
            },
        },
        {
            "id": 3,
            "name": "Radlicka 52",
            "address": "Radlicka 52, Prague 5",
            "coordinates": [51.48, -0.1],
            "price": "30 000",
            "prop_type": "house",
            "images": [
                "https://images.pexels.com/photos/1643389/pexels-photo-1643389.jpeg",
                "https://images.pexels.com/photos/259962/pexels-photo-259962.jpeg",
                "https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg",
            ],
            "prop_size_kk": 4,
            "prop_size_m2": 75,
            "energy_class": "A+",
            "rk": False,
            "floor": 2,
            "parking": 3,
            "elevator": False,
            "features": ["Garden", "Fireplace", "Spacious Rooms"],
            "neighborhood": {
                "description": "A suburban area with lots of greenery...",
                "amenities": ["Schools", "Supermarkets", "Clinics"],
                "transport": ["Bus", "Metro"],
            },
            "average_rent": "28 500",
            "pricing_details": {
                "one_time_payments": [
                    {"name": "Security Deposit", "amount": "60 000 "},
                    {"name": "Agency Fee", "amount": "30 000 "},
                ],
                "monthly_payments": [
                    {"name": "Rent", "amount": "30 000 "},
                    {"name": "Utilities", "amount": "3 500 "},
                ],
            },
            "contact": {
                "agent": "Eva Novak",
                "phone": "+420 123 123 456",
                "email": "eva.novak@example.com",
            },
        },
    ]